name: geiger_toolbox
description: A cyber security geiger toolbox for MSEs


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.3
  #progress animations
  # we might not need this
  percent_indicator: ^3.0.1
  #indicator gauge
  pretty_gauge: ^1.0.0

  #add multiple color gradient to text
  simple_gradient_text: ^1.2.2
  #to deserialize/serialize ui related data
  json_annotation: ^4.3.0
  #to generate qr code
  qr_flutter: ^4.0.0
  # to scan qr code, only tested on ios,android
  qr_code_scanner: ^0.5.2
  #to check for camera permission
  permission_handler: ^8.2.2
  device_info_plus: 3.2.1

  cloud_replication_package:
    git:
      url: git://github.com/cyber-geiger/toolbox-replication.git
      ref: development

#  cloud_replication_package:
#    path: ../toolbox-replication

  #state management, dependency injection
  get: ^4.6.1
  #cache data
  get_storage: ^2.0.3
  #for bar chart and other related chart
  charts_flutter: ^0.12.0
  toolbox_indicator_test: ^2.0.0
  geiger_api: ^0.7.2
  geiger_localstorage: ^0.6.38
  #local notification
  flutter_local_notifications: ^9.2.0
  share_plus: ^3.0.4
  #helps to resize app size on windows
  window_manager: ^0.1.5
  #flutter ui utils, as circular animation too
  getwidget: ^2.0.4
  #help to open web links
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  #runner for generating json
  build_runner: ^2.1.4
  flutter_lints: ^1.0.4
  flutter_native_splash: ^2.0.4

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#ffffff"
  image: assets/images/geiger_splash.png
  image_dark: assets/images/geiger_splash.png

  android: true
  ios: true


flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  fonts:
     - family:  GeigerIcon
       fonts:
         - asset: assets/fonts/GeigerIcon.ttf
     - family: Nunito
       fonts:
         - asset: assets/fonts/Nunito-Regular.ttf


#Todo
#add to web/index.html
#<script src="https://cdn.jsdelivr.net/npm/jsqr@1.3.1/dist/jsQR.min.js"></script>
