name: External Github Action Flow (triggerred from other repositories)
on:
  workflow_dispatch:

jobs:
  unit-test:
    name: -> Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-18.04, windows-2019, macos-10.15]
        os: [ubuntu-18.04]
    # runs-on: ubuntu-latest
    # container:
    #   image:  google/dart:latest
    steps:
    # Set up Flutter.
    - name: -> Decode the keystore
      id: decode_keystore
      uses: timheuer/base64-to-file@v1
      with:
        fileName: 'keystore.jks'
        encodedString: ${{ secrets.KEY_JKS }}
    - name: -> Relocate the keystore file
      run: cp ${{steps.decode_keystore.outputs.filePath}} android/
    - name: -> Setup Flutter environment
      uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8
      with:
        channel: master
    - run: flutter doctor -v

    # Checkout gallery code and get packages.
    - name: -> Checkout gallery code
      uses: actions/checkout@v2
    - name: -> Get the packages
      run: flutter pub get
    - name: -> Update the latest version of geiger packages - geiger_localstorage/...
      run: flutter pub upgrade geiger_localstorage

    # Analyze, check formatting, and run unit tests.
    - name: -> Analyze the project
      run: flutter analyze
    - name: -> Check the format
      run: flutter format --set-exit-if-changed --dry-run .
    # Run the unit tests
    - name: -> Run unit tests
      run: flutter test
    - name: -> Generate apk file
      env:
        KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        ALIAS_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      run: flutter build apk --release
    - uses: actions/upload-artifact@v2
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk

    # Trigger other to test the application
    # - name: -> Trigger the external_workflows on other repositories
    #   run: |
    #       curl \
    #       -X POST \
    #       -u '${{secrets.USER_NAME}}:${{secrets.APPLICATION_ACCESS_TOKEN}}' \
    #       -H "Accept: application/vnd.github.v3+json" \
    #       https://api.github.com/repos/luongnv89/geiger_toolbox_api_flutter/actions/workflows/main.yaml/dispatches \
    #       -d '{"ref":"refs/heads/main"}'