name: Internal Github Action Flow
on:
  push:
    branches:
    - development
  pull_request:
    # branches:
    # - development
    # - main
jobs:
  unit-test:
    name: -> Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-18.04, windows-2019, macos-10.15]
        os: [ubuntu-18.04]
    # runs-on: ubuntu-latest
    # container:
    #   image:  google/dart:latest
    steps:
    # Get the source code
    - name: -> Get the source code
      uses: actions/checkout@v2
    # Create the keystore file
    - name: -> Decode the keystore
      id: decode_keystore
      uses: timheuer/base64-to-file@v1
      with:
        fileName: 'keystore.jks'
        encodedString: ${{ secrets.KEY_JKS }}
    - name: -> Relocate the keystore file
      run: cp ${{steps.decode_keystore.outputs.filePath}} android/
    # Set up Flutter.
    - name: -> Setup Flutter environment
      uses: subosito/flutter-action@v1
      with:
        channel: stable
    - name: -> Check the flutter environment
      run: flutter doctor -v

    # Install the dependencies
    - name: -> Get packages
      run: flutter pub get

    # Analyze, check formatting, and run unit tests.
    - name: -> Analyze the project
      run: flutter analyze
    - name: -> Check the format
      run: flutter format --set-exit-if-changed --dry-run .
    # Run the unit tests
    - name: -> Run unit tests
      run: flutter test
    # Generate the apk file
    - name: -> Generate apk file
      env:
        KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        ALIAS_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      run: flutter build apk --release
    # Upload the artifact
    - name: -> Upload the generated .apk file
      uses: actions/upload-artifact@v2
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
    # Trigger other to test the application
    # - name: -> Trigger the external_workflows on other repositories
    #   run: |
    #       curl \
    #       -X POST \
    #       -u '${{secrets.USER_NAME}}:${{secrets.APPLICATION_ACCESS_TOKEN}}' \
    #       -H "Accept: application/vnd.github.v3+json" \
    #       https://api.github.com/repos/cyber-geiger/toolbox-storage/actions/workflows/external_workflow.yaml/dispatches \
    #       -d '{"ref":"refs/heads/development"}'

    # # publish to pub.dev
    # - name: -> Check before publish to pub.dev
    #   run: dart pub publish --dry-run
    # - name: -> Setup credentials
    #   run: |
    #     cat <<EOF > $PUB_CACHE/credentials.json
    #     {
    #       "accessToken":"${{ secrets.OAUTH_ACCESS_TOKEN }}",
    #       "refreshToken":"${{ secrets.OAUTH_REFRESH_TOKEN }}",
    #       "idToken":"${{ secrets.OAUTH_ID_TOKEN }}",
    #       "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
    #       "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
    #       "expiration": 1630429975373
    #     }
    #     EOF
    # - name: -> Publish package
    #   run: dart pub publish -f